periodic: unix:///tmp/periodic.sock
thread: 10
root: images
enable-guetzli: true
enable-remove: true
enable-save: true
guetzli:
  output: guetzli
  lock-count: 1
  lock-name: guetzli

resizes:
  - func: resize-image-fw1024
    width: 1024
    output: resize-image
    suffix: _fw1024.jpg
  - func: resize-image-fw500
    width: 500
    output: resize-image
    suffix: _fw500.jpg
  - func: resize-image-fw192
    width: 192
    output: resize-image
    suffix: _fw192.jpg
  - func: resize-image-fw64
    width: 64
    output: resize-image
    suffix: _fw64.jpg
